version: '3'
services:
    app:
        container_name: CuriousJr_Certi
        restart: always
        build: .
        ports: 
            - '3000:8080'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'